server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    config:
      profile: dev
      label: main
    gateway:
#      서비스에 맞게 추후 수정
#      routes:
#        - id:
#          uri: lb://
#          predicates:
#            - Path=
  config:
    import: http://localhost:8888