server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service

  cloud:
    config:
      profile: dev
      label: main

  gateway:
    # 서비스 라우팅은 여기에

management:
  endpoints:
    web:
      exposure:
        include: "*"