server:
  port: 60003

spring:
  application:
    name: analysis-service
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
