server:
  port: 8000

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: apigateway-service
  cloud:
    config:
      profile: dev
      label: main
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: dashboard-service
          uri: lb://DASHBOARD-SERVICE
          predicates:
            - Path=/dashboard/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            # - AuthorizationHeaderFilter
        - id: llm-service
          uri: lb://LLM-SERVICE
          predicates:
            - Path=/llm/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: reward-service
          uri: lb://REWARD-SERVICE
          predicates:
            - Path=/reward/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates: 
            - Path=/admin/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: analysis-service
          uri: lb://ANALYSIS-SERVICE
          predicates: 
            - Path=/analysis/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            # - AuthorizationHeaderFilter
            
  jwt:
    issuer: http://localhost
    secret: hw4Mcjad0qJzSqFDwgm0uvJ3JpNY8ay7

              
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
