server:
  port: 60005

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: reward-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:MODIVE}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}  
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
