server:
  port: 8761

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: service-discovery
  cloud:
    config:
      profile: dev
      label: main

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
